name: Test Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Download soundpipe native library
      uses: dawidd6/action-download-artifact@v6
      with:
        name: SoundPipe-Windows-Linux
        branch: master
        event: push
        workflow_conclusion: success
        repo: https://github.com/YellowDogMan/SharpPipe
        path: ./SharpPipe
        github_token: ${{secrets.GITHUB_TOKEN}}
      

    - name: Build
      working-directory: ./SharpPipe
      run: dotnet pack -c Release