name: Build Library
run-name: ${{ github.actor }} is building SharpPipe

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Download soundpipe native library
      run: |
        Invoke-WebRequest https://github.com/Yellow-Dog-Man/soundpipe/releases/latest/download/SoundPipe-Windows-Linux.zip -OutFile .\SoundPipe-Windows-Linux.zip
        Expand-Archive .\SoundPipe-Windows-Linux.zip -DestinationPath .\SharpPipe
      
    - name: Build
      working-directory: ./SharpPipe
      run: dotnet pack -c Release
    
    - name: Put a big red bow on it
      uses: actions/upload-artifact@v4
      with:
        name: SharpPipe
        path: SharpPipe/bin/Release/*.nupkg
      