name: Publish Library
run-name: ${{ github.actor }} is publishing SharpPipe

on:  
  release:
    types: [published]


jobs:
  publish:
    env:
      VERSION: ${{ github.event.release.tag_name }}
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Download soundpipe native library
      run: |
        Invoke-WebRequest https://github.com/Yellow-Dog-Man/soundpipe/releases/latest/download/SoundPipe-Windows-Linux.zip -OutFile .\SoundPipe-Windows-Linux.zip
        Expand-Archive .\SoundPipe-Windows-Linux.zip -DestinationPath .\SharpPipe
      
    - name: Build
      working-directory: ./SharpPipe
      run: dotnet pack -c Release -p:Version=${{ env.VERSION }} -p:PackageVersion=${{ env.VERSION }}
    
    - name: Nuget Publish
      run: dotnet nuget push .\LiteNetLib\bin\Release\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json